### ISSUE TITLE
"Run Makefile" is broken in CLion on Windows (with Cygwin toolchain active)

### ISSUE THREAD

**Issue by Zastai** [kropp/intellij-makefile#161]
Trying to do so results in
```
Error running 'Makefile': Cannot run program "\usr\bin\make" (in directory "<directory containing makefile>"): CreateProcess error=2, The system cannot find the file specified
```
and there seems to be no way to specify the make executable to use.

**Comment by kropp** [comment]
There is `File | Settings | Build, Execution, Deployment | Build Tools | Make` settings page.
You can change path to Make executable there, and also point it to use Cygwin.

**Comment by Zastai** [comment]
That makes me feel silly - I did do a settings search, but for "Makefile" and that only got me the color scheme. And it looks like then using backspace to reduce the search term to "Make" does not actually refresh the search results.

**Comment by kropp** [comment]
@Zastai this is a good point, I'll check with IntelliJ folks if it is bug and also if it is possible to provide multiple search terms for a settings page.

**Comment by sampleref** [comment]
When trying to build with _CLion 2020.2 with Makefile project(make) **WSL 1 Ubuntu 16.04**_ 

```
2020-08-15 15:01:05,961 [16441590]   INFO - m.pty4j.windows.WindowsVersion - Windows version: 10.0.17763 
2020-08-15 15:01:06,202 [16441831]   WARN - .configurations.PtyCommandLine - Couldn't run process with PTY 
java.io.IOException: Couldn't create PTY
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:74)
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:49)
	at com.pty4j.PtyProcessBuilder.start(PtyProcessBuilder.java:109)
	at com.intellij.execution.configurations.PtyCommandLine.doStartProcessWithPty(PtyCommandLine.java:238)
	at com.intellij.execution.configurations.PtyCommandLine.startProcessWithPty(PtyCommandLine.java:196)
	at com.intellij.execution.configurations.PtyCommandLine.startProcess(PtyCommandLine.java:139)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:422)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:99)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:47)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:24)
	at name.kropp.intellij.makefile.MakefileRunConfiguration$getState$1.startProcess(MakefileRunConfiguration.kt:77)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:147)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:208)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.pty4j.windows.WinPtyException: Error running process: CreateProcess failed. Code 2
	at com.pty4j.windows.WinPty.<init>(WinPty.java:127)
	at com.pty4j.windows.WinPtyProcess.<init>(WinPtyProcess.java:71)
	... 44 more
2020-08-15 15:01:06,207 [16441836]   INFO - xecution.runners.ExecutionUtil - Error running 'all':<br>Cannot run program "\usr\bin\make" (in directory "C:\Users\User1\workspace\joom\jum"): CreateProcess error=2, The system cannot find the file specified 
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\usr\bin\make" (in directory "C:\Users\User1\workspace\joom\jum"): CreateProcess error=2, The system cannot find the file specified
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:426)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:99)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:47)
	at com.intellij.execution.process.KillableProcessHandler.<init>(KillableProcessHandler.java:37)
	at com.intellij.execution.process.ColoredProcessHandler.<init>(ColoredProcessHandler.java:24)
	at name.kropp.intellij.makefile.MakefileRunConfiguration$getState$1.startProcess(MakefileRunConfiguration.kt:77)
	at com.intellij.execution.configurations.CommandLineState.execute(CommandLineState.java:61)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:29)
	at com.intellij.execution.runners.DefaultRunProgramRunner$execute$1.invoke(DefaultRunProgramRunner.kt:12)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:147)
	at com.intellij.execution.impl.ExecutionManagerImpl$startRunProfile$1.invoke(ExecutionManagerImpl.kt:60)
	at com.intellij.execution.impl.ExecutionManagerImpl$doStartRunProfile$startRunnable$1.run(ExecutionManagerImpl.kt:208)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:967)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:839)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:449)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:497)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: Cannot run program "\usr\bin\make" (in directory "C:\Users\User1\workspace\joom\jum"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:457)
	at com.intellij.execution.configurations.PtyCommandLine.startProcess(PtyCommandLine.java:157)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:422)
	... 38 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 42 more
2020-08-15 15:01:08,444 [16444073]   INFO - rationStore.ComponentStoreImpl - Saving Project(name=re, containerState=ACTIVE, componentStore=C:\Users\User1\workspace\joom\jum)RunManager took 15 ms
``` 


Any suggestions would really help

**Comment by Zastai** [comment]
My suggestion would be to file a new issue instead of commenting on an unrelated one.
