### ISSUE TITLE
[PR ready] Comments not recognized properly since 3.1

### ISSUE THREAD

**Issue by LANGERGabrielle** [kropp/intellij-makefile#167]
Makefile:

db-create:
	"('')"
.PHONY: db-create

\# --------------------------------------------------------

Expected the comment to be correctly identified:

![image](https://user-images.githubusercontent.com/29628106/83017633-4c719380-a024-11ea-8773-cf64fb1678e0.png)

Actual:

![image](https://user-images.githubusercontent.com/29628106/83017503-1207f680-a024-11ea-92bb-41011603e9fb.png)

Using phpstorm 2020.1
Reproducible in idea ultimate 2020.1

**Comment by LANGERGabrielle** [comment]
[Patch passing test on 27f204ddd0a09d85b5f3206b7a1d80cf40617bac](https://github.com/kropp/intellij-makefile/files/4689855/167.zip)

And failing on master:
com.intellij.rt.execution.junit.FileComparisonFailure: expected:<...t(\t)('\t')
            [PsiElement(string)('"('')"')
            PsiElement(EOL)('\n\n')
      PsiComment(COMMENT)('# --------------------------------------------------------')]> but was:<...t(\t)('\t')
            [MakefileStringImpl(STRING)
              PsiElement(")('"')
              PsiElement(()('(')
              PsiElement(')(''')
              PsiElement(')(''')
              PsiElement())(')')
              PsiElement(")('"')
            PsiElement(EOL)('\n')
          PsiElement(EOL)('\n')
      PsiElement(chars)('#')
      PsiErrorElement:'!=', $, '+=', '::=', ':=', '=' or '?=' expected, got '--------------------...'
        <empty list>
      PsiWhiteSpace(' ')
      PsiElement(chars)('--------------------------------------------------------')
      PsiErrorElement:'!=', $, '+=', ':', '::=', ':=', '=' or '?=' expected
        <empty list>]>
        at com.intellij.testFramework.UsefulTestCase.assertSameLinesWithFile(UsefulTestCase.java:878)
        at com.intellij.testFramework.UsefulTestCase.assertSameLinesWithFile(UsefulTestCase.java:852)
        at com.intellij.testFramework.UsefulTestCase.assertSameLinesWithFile(UsefulTestCase.java:842)
        at com.intellij.testFramework.ParsingTestCase.doCheckResult(ParsingTestCase.java:414)
        at com.intellij.testFramework.ParsingTestCase.doCheckResult(ParsingTestCase.java:377)
        at com.intellij.testFramework.ParsingTestCase.checkResult(ParsingTestCase.java:350)
        at com.intellij.testFramework.ParsingTestCase.doTest(ParsingTestCase.java:304)
        at com.intellij.testFramework.ParsingTestCase.doTest(ParsingTestCase.java:289)
        at MakefileParserTest.testIssue167(MakefileParserTest.kt:79)

**Comment by LANGERGabrielle** [comment]
Seems to originate from c15b4ff151ab67a5007d6be2458942b041b198c4
